language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_FLAGS=""
  - COMPOSER_FLAGS="--prefer-lowest"

before_script:
    - composer update ${COMPOSER_FLAGS}

script: bin/phpunit

notifications:
  irc: "irc.freenode.org#fsi-open"
